name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install

      - name: Lint Format Check
        run: yarn run lint

      - name: Jest Integration Test
        run: yarn test --passWithNoTests

      - name: Build
        run: yarn build

      - name: Build:StoryBook
        run: yarn build-storybook
